"""Initial schema

Revision ID: 60a7669178f4
Revises:
Create Date: 2026-08-23 15:53:06.344045

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "60a7669178f4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scan_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("universe_size", sa.Integer(), nullable=True),
        sa.Column("data_valid", sa.Integer(), nullable=True),
        sa.Column("filtered_count", sa.Integer(), nullable=True),
        sa.Column("candidate_count", sa.Integer(), nullable=True),
        sa.Column("final_count", sa.Integer(), nullable=True),
        sa.Column("market_regime", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scan_runs_id"), "scan_runs", ["id"], unique=False)
    op.create_table(
        "stocks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("company_name", sa.String(), nullable=False),
        sa.Column("exchange", sa.String(), nullable=False),
        sa.Column("sector", sa.String(), nullable=True),
        sa.Column("industry", sa.String(), nullable=True),
        sa.Column("isin", sa.String(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stocks_id"), "stocks", ["id"], unique=False)
    op.create_index(op.f("ix_stocks_symbol"), "stocks", ["symbol"], unique=True)
    op.create_table(
        "candles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("timestamp", sa.Date(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=False),
        sa.Column("adjusted_close", sa.Float(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["stocks.symbol"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_candles_id"), "candles", ["id"], unique=False)
    op.create_index(op.f("ix_candles_symbol"), "candles", ["symbol"], unique=False)
    op.create_index(
        op.f("ix_candles_timestamp"), "candles", ["timestamp"], unique=False
    )
    op.create_table(
        "indicators",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("timestamp", sa.Date(), nullable=False),
        sa.Column("sma20", sa.Float(), nullable=True),
        sa.Column("sma50", sa.Float(), nullable=True),
        sa.Column("sma200", sa.Float(), nullable=True),
        sa.Column("ema20", sa.Float(), nullable=True),
        sa.Column("ema50", sa.Float(), nullable=True),
        sa.Column("rsi14", sa.Float(), nullable=True),
        sa.Column("macd", sa.Float(), nullable=True),
        sa.Column("adx", sa.Float(), nullable=True),
        sa.Column("atr14", sa.Float(), nullable=True),
        sa.Column("relative_volume", sa.Float(), nullable=True),
        sa.Column("return_20d", sa.Float(), nullable=True),
        sa.Column("return_60d", sa.Float(), nullable=True),
        sa.Column("relative_strength_20d", sa.Float(), nullable=True),
        sa.Column("relative_strength_60d", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["stocks.symbol"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_indicators_id"), "indicators", ["id"], unique=False)
    op.create_index(
        op.f("ix_indicators_symbol"), "indicators", ["symbol"], unique=False
    )
    op.create_index(
        op.f("ix_indicators_timestamp"), "indicators", ["timestamp"], unique=False
    )
    op.create_table(
        "news",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("sentiment", sa.String(), nullable=True),
        sa.Column("risk_level", sa.String(), nullable=True),
        sa.Column("summary", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["stocks.symbol"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_news_id"), "news", ["id"], unique=False)
    op.create_table(
        "recommendations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("recommendation_date", sa.Date(), nullable=False),
        sa.Column("setup_type", sa.String(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("market_regime", sa.String(), nullable=False),
        sa.Column("current_price", sa.Float(), nullable=False),
        sa.Column("entry_low", sa.Float(), nullable=False),
        sa.Column("entry_high", sa.Float(), nullable=False),
        sa.Column("stop_loss", sa.Float(), nullable=False),
        sa.Column("target_1", sa.Float(), nullable=False),
        sa.Column("target_2", sa.Float(), nullable=False),
        sa.Column("risk_reward", sa.Float(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("capital_required", sa.Float(), nullable=False),
        sa.Column("max_loss", sa.Float(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("ai_explanation", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["scan_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["symbol"],
            ["stocks.symbol"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recommendations_id"), "recommendations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_recommendations_recommendation_date"),
        "recommendations",
        ["recommendation_date"],
        unique=False,
    )
    op.create_table(
        "recommendation_outcomes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recommendation_id", sa.Integer(), nullable=False),
        sa.Column("entry_price", sa.Float(), nullable=True),
        sa.Column("entry_date", sa.Date(), nullable=True),
        sa.Column("exit_price", sa.Float(), nullable=True),
        sa.Column("exit_date", sa.Date(), nullable=True),
        sa.Column("exit_reason", sa.String(), nullable=True),
        sa.Column("gross_pnl", sa.Float(), nullable=True),
        sa.Column("charges", sa.Float(), nullable=True),
        sa.Column("net_pnl", sa.Float(), nullable=True),
        sa.Column("return_pct", sa.Float(), nullable=True),
        sa.Column("holding_days", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recommendation_outcomes_id"),
        "recommendation_outcomes",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_recommendation_outcomes_id"), table_name="recommendation_outcomes"
    )
    op.drop_table("recommendation_outcomes")
    op.drop_index(
        op.f("ix_recommendations_recommendation_date"), table_name="recommendations"
    )
    op.drop_index(op.f("ix_recommendations_id"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_news_id"), table_name="news")
    op.drop_table("news")
    op.drop_index(op.f("ix_indicators_timestamp"), table_name="indicators")
    op.drop_index(op.f("ix_indicators_symbol"), table_name="indicators")
    op.drop_index(op.f("ix_indicators_id"), table_name="indicators")
    op.drop_table("indicators")
    op.drop_index(op.f("ix_candles_timestamp"), table_name="candles")
    op.drop_index(op.f("ix_candles_symbol"), table_name="candles")
    op.drop_index(op.f("ix_candles_id"), table_name="candles")
    op.drop_table("candles")
    op.drop_index(op.f("ix_stocks_symbol"), table_name="stocks")
    op.drop_index(op.f("ix_stocks_id"), table_name="stocks")
    op.drop_table("stocks")
    op.drop_index(op.f("ix_scan_runs_id"), table_name="scan_runs")
    op.drop_table("scan_runs")
    # ### end Alembic commands ###
