"""add daily_update_runs table

Revision ID: 77d05085a7fc
Revises: 60a7669178f4
Create Date: 2026-08-23 17:49:28.863998

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77d05085a7fc"
down_revision: Union[str, Sequence[str], None] = "60a7669178f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_update_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_date", sa.Date(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("positions_checked", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_daily_update_runs_id"), "daily_update_runs", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_daily_update_runs_run_date"),
        "daily_update_runs",
        ["run_date"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_daily_update_runs_run_date"), table_name="daily_update_runs")
    op.drop_index(op.f("ix_daily_update_runs_id"), table_name="daily_update_runs")
    op.drop_table("daily_update_runs")
    # ### end Alembic commands ###
